$INPUT_RECORD_SEPARATOR: String?

class BufferedTokenizer
  SPLIT_LIMIT: Integer
  @delimiter: String
  @input: Array[String]
  @tail: String
  @overlap: Integer

  attr_reader overlap: Integer

  def initialize: (?String delimiter) -> void
  def size: () -> Integer
  def extract: (String data) -> Array[String]
  def flush: () -> String

  private

  def consolidate_input: (Array[String] entities) -> void
  def rejoin_split_delimiter: (String data) -> String
end

Buftok: singleton(BufferedTokenizer)
